import jsPDF from 'jspdf';
import { ProjectTimeline } from '@/types';

export function exportTimelineToPDF(timeline: ProjectTimeline) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  // Helper function to add text with word wrap
  const addText = (text: string, fontSize: number = 12, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    if (isBold) {
      doc.setFont('helvetica', 'bold');
    } else {
      doc.setFont('helvetica', 'normal');
    }
    const lines = doc.splitTextToSize(text, pageWidth - margin * 2);
    doc.text(lines, margin, yPosition);
    yPosition += lines.length * (fontSize * 0.4) + 5;
  };

  // Helper to check page overflow
  const checkPageOverflow = (requiredSpace: number = 20) => {
    if (yPosition + requiredSpace > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      yPosition = 20;
    }
  };

  // Title
  doc.setFillColor(30, 64, 175); // architectural-blue
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Project Timeline Report', margin, 25);
  yPosition = 50;
  doc.setTextColor(0, 0, 0);

  // Project Summary
  addText('Project Summary', 16, true);
  addText(timeline.project_summary);
  yPosition += 5;

  // Total Duration
  checkPageOverflow(30);
  addText('Estimated Project Duration', 16, true);
  addText(
    `${timeline.total_duration_days_min} - ${timeline.total_duration_days_max} days (${Math.round(
      timeline.total_duration_days_min / 7
    )}-${Math.round(timeline.total_duration_days_max / 7)} weeks)`
  );
  yPosition += 10;

  // Phases
  checkPageOverflow(40);
  addText('Project Phases', 16, true);
  yPosition += 5;

  timeline.phases.forEach((phase, index) => {
    checkPageOverflow(40);

    // Phase number and name
    doc.setFillColor(240, 240, 240);
    doc.rect(margin, yPosition - 5, pageWidth - margin * 2, 10, 'F');

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 64, 175);
    doc.text(`${index + 1}. ${phase.name}`, margin + 2, yPosition);
    yPosition += 12;
    doc.setTextColor(0, 0, 0);

    // Phase details
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const descLines = doc.splitTextToSize(phase.description, pageWidth - margin * 2 - 4);
    doc.text(descLines, margin + 2, yPosition);
    yPosition += descLines.length * 5 + 3;

    doc.setFont('helvetica', 'bold');
    doc.text(
      `Duration: ${phase.duration_days_min}-${phase.duration_days_max} days`,
      margin + 2,
      yPosition
    );
    yPosition += 10;
  });

  // Assumptions
  if (timeline.assumptions && timeline.assumptions.length > 0) {
    checkPageOverflow(40);
    addText('Assumptions', 16, true);
    timeline.assumptions.forEach((assumption, index) => {
      checkPageOverflow(15);
      addText(`• ${assumption}`, 11);
    });
    yPosition += 5;
  }

  // Risk Factors
  if (timeline.risk_factors && timeline.risk_factors.length > 0) {
    checkPageOverflow(40);
    addText('Risk Factors', 16, true);
    timeline.risk_factors.forEach((risk, index) => {
      checkPageOverflow(15);
      doc.setTextColor(200, 50, 50);
      addText(`⚠ ${risk}`, 11);
      doc.setTextColor(0, 0, 0);
    });
  }

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Project Timeline AI - ${new Date().toLocaleDateString()}`,
      margin,
      doc.internal.pageSize.getHeight() - 10
    );
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, doc.internal.pageSize.getHeight() - 10);
  }

  // Save the PDF
  doc.save(`project-timeline-${new Date().getTime()}.pdf`);
}
